Transform: AWS::Serverless-2016-10-31
Description: Serverless Visitor Counter Application

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

Resources:
  VisitorCounterApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: VisitorCounterApi
      StageName: Prod
      Cors:
        AllowMethods:
          - GET
          - PUT
          - POST
          - DELETE
          - OPTIONS
          - HEAD
          - PATCH
        AllowHeaders:
          - "*"
        AllowOrigin: 
          - "*"

  VisitorCounterTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: "resume2"

  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: VisitorCounter/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Sid: DynamoDBAccess
              Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:Scan
              Resource: !GetAtt VisitorCounterTable.Arn
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref VisitorCounterTable
      Events:
        GetVisitorCount:
          Type: Api
          Properties:
            RestApiId: !Ref VisitorCounterApi
            Path: /VisitorCounter
            Method: ANY

Outputs:
  VisitorCounterApi:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${VisitorCounterApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/VisitorCounter"
  VisitorCounterFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt VisitorCounterFunction.Arn
  VisitorCounterTableName:
    Description: DynamoDB Table Name
    Value: !Ref VisitorCounterTable
