Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless Visitor Counter Application

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  VisitorCounterTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: "resume"

  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: VisitorCounter/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:  # Changed from DynamoDBReadWriteAccess
            TableName: !Ref VisitorCounterTable  # Fixed reference
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref VisitorCounterTable  # Fixed reference
      Events:
        GetVisitorCount:
          Type: Api
          Properties:
            Path: /VisitorCounter
            Method: get
            Cors:  # Added CORS configuration
              AllowMethods: ["GET"]
              AllowHeaders: ["*"]
              AllowOrigin: "'*'"

Outputs:
  VisitorCounterApi:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/VisitorCounter"
  VisitorCounterFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt VisitorCounterFunction.Arn
  VisitorCounterTableName:
    Description: DynamoDB Table Name
    Value: !Ref VisitorCounterTable
