Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless Visitor Counter Application

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  VisitorCounterTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: "resume" #Added Table Name

  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: VisitorCounter/  # Changed CodeUri to visitor_counter_lambda
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
        - DynamoDBReadWriteAccess: # Added DynamoDB permissions
            TableName: !Ref VisitorCounterTableFunction
      Environment: # Added Environment Variables
        Variables:
          DYNAMODB_TABLE_NAME: !Ref VisitorCounterTableFunction # Pass table name to function
      Events:
        GetVisitorCount: # Changed the name of the event
          Type: Api
          Properties:
            Path: /VisitorCounter
            Method: get

Outputs:
  VisitorCounterApi:
    Description: API Gateway endpoint URL for the Visitor Counter API
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/VisitorCounter" # Correct way to get API URL
  VisitorCounterFunctionArn:
    Description: Visitor Counter Lambda Function ARN
    Value: !GetAtt VisitorCounterFunction.Arn
  VisitorCounterFunctionIamRoleArn:
    Description: Implicit IAM Role created for Visitor Counter function
    Value: !GetAtt VisitorCounterFunctionRole.Arn
  VisitorCounterTableName: #Added Table Name Output
    Description: Visitor Counter DynamoDB Table Name
    Value: !Ref VisitorCounterTable
