Transform: AWS::Serverless-2016-10-31
Description: Serverless Visitor Counter Application

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

Resources:
  ## 1) Define your own API with CORS ##
  VisitorCounterApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      TracingEnabled: true
      Cors:
        AllowMethods: "'ANY'"
        AllowHeaders: "'*'"
        AllowOrigins: "'*'"    # <-- Make sure this key is present

  VisitorCounterTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: "resume"

  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: VisitorCounter/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      ## 2) Attach DynamoDB policy (you should already have fixed this) ##
      Policies:
        - PolicyName: VisitorCounterDynamoDBPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: DynamoDBAccess
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Scan
                Resource: !GetAtt VisitorCounterTable.Arn
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref VisitorCounterTable
      Events:
        GetVisitorCount:
          Type: Api
          Properties:
            RestApiId: !Ref VisitorCounterApi   # <— point at your explicit API
            Path: /VisitorCounter
            Method: ANY

Outputs:
  VisitorCounterApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${VisitorCounterApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/VisitorCounter"
  VisitorCounterFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt VisitorCounterFunction.Arn
  VisitorCounterTableName:
    Description: DynamoDB Table Name
    Value: !Ref VisitorCounterTable
