name: SAM Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          pip install --upgrade aws-sam-cli
          sam --version

      - name: Validate SAM template
        run: sam validate --template template.yaml

      - name: Debug project structure
        run: |
          echo "Current directory:"
          pwd
          echo "Files:"
          ls -la
          echo "VisitorCounter contents:"
          ls -la VisitorCounter/

      - name: SAM Deploy
        run: |
          sam deploy \
            --template-file template.yaml \
            --stack-name my-resume-counter-stack1 \
            --region ${{ secrets.AWS_REGION }} \
            --capabilities CAPABILITY_IAM \
            --resolve-s3 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --debug

      - name: Upload frontend to S3
        run: |
          aws s3 sync frontend/ s3://${{ secrets.S3_BUCKET_NAME }}/
